name: 'Version appendix action'
description: 'Create an appendix to a semantic version based on current branch and run number.'
inputs:
  github_ref:
    description: 'Current github ref (GITHUB_REF)'
    required: true
  github_run_number:
    description: 'Current github run number (GITHUB_RUN_NUMBER)'
    required: true
outputs:
  appendix:
    description: 'Created version appendix'
runs:
  using: 'node12'
  main: 'versioning.js'
