name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  github_ref:
    description: 'Current github ref (GITHUB_REF)'
    required: true
  github_run_number:
    description: 'Current github run number (GITHUB_RUN_NUMBER)'
    required: true
outputs:
  appendix:
    description: 'Version appendix'
runs:
  using: 'ubuntu-latest'
  main: 'versioning.js'
